version: 0.2

phases:

  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - chmod +x ./scripts/*.sh
      - ./gradlew build

  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
      - cp ./scripts/appspec-production.yml ./appspec.yml

artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - scripts/**
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'